"""Report Generation Agent placeholder implementation."""

from __future__ import annotations

from market_mapper.schemas.models import Report, ReportSection
from market_mapper.workflow.contracts import (
    ReportGenerationNodeInput,
    ReportGenerationNodeOutput,
)


def run_report_generation(
    node_input: ReportGenerationNodeInput,
) -> ReportGenerationNodeOutput:
    """Create a placeholder Markdown report from the comparison result."""

    report = Report(
        run_id=node_input.run_id,
        title="Market Mapper Placeholder Report",
        executive_summary="Placeholder executive summary generated by report node.",
        sections=[
            ReportSection(
                heading="Comparison Overview",
                body="Placeholder report section based on comparison output.",
            )
        ],
        markdown_body="# Placeholder Report\n\nThis report was generated by the workflow skeleton.",
        source_document_ids=[document.id for document in node_input.source_documents],
    )
    return ReportGenerationNodeOutput(
        report=report,
        summary="Report generation placeholder created a report.",
        next_route="executor",
    )
